# Run repoman on travis
# https://github.com/urras/repoman-travis
#
language: python
python:
    - "3.4.1"
env:
    - PORTAGE_VER="2.2.14"
before_script:
    - mkdir travis-overlay
    - mv !(travis-overlay) travis-overlay/
    - mv .git travis-overlay/
    - curl -3 "http://distfiles.gentoo.org/distfiles/portage-${PORTAGE_VER}.tar.bz2" -o portage-${PORTAGE_VER}.tar.bz2
    - curl -3 "http://distfiles.gentoo.org/snapshots/portage-latest.tar.xz" -o portage-latest.tar.xz
    - curl -3 "https://raw.githubusercontent.com/urras/repoman-travis/master/spinner.sh" -o spinner.sh
    - sudo chmod 777 /etc/passwd /etc/group /etc /usr spinner.sh
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - mkdir -p /etc/portage/ /usr/portage/distfiles
    - tar xjf portage-${PORTAGE_VER}.tar.bz2
    - tar xJf portage-latest.tar.xz -C /usr/
    - cp portage-${PORTAGE_VER}/cnf/repos.conf /etc/portage/
    - rsync --recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --checksum --quiet rsync://rsync.gentoo.org/gentoo-portage /usr/portage
    - ln -s /usr/portage/profiles/base/ /etc/portage/make.profile
    - curl -3 "http://www.gentoo.org/dtd/metadata.dtd" -o /usr/portage/distfiles/metadata.dtd
    - cd travis-overlay
script:
    - ./../spinner.sh "./../portage-${PORTAGE_VER}/bin/repoman full -d"
# You can append own scripts after this line
